In [1]:
import pandas as pd
import openpyxl

In [2]:
product_sales = pd.read_csv(r'C:\Users\Admin\RBAC\Round3_RBAC\ProductSales.csv')
product_map = pd.read_csv(r'C:\Users\Admin\RBAC\Round3_RBAC\ProductMapping.csv')
voucher_map = pd.read_csv(r'C:\Users\Admin\RBAC\Round3_RBAC\VoucherMapping.csv')
segment = pd.read_excel(r'C:\Users\Admin\RBAC\r3_segmentation1.xlsx', index_col=0)
RFM_value = pd.read_csv(r'C:\Users\Admin\RBAC\RFM_Value_Extracted.csv', index_col=0)

In [3]:
product_map_nonprefix = pd.read_excel(r'C:\Users\Admin\RBAC\Product_NonPrefix.xlsx', index_col=0)

In [4]:
product_map_nonprefix

      FoodCode  NAME_NOPREFIX
0          485          COMBO
1         2952          COMBO
2         2949      PROMOTION
3          561      PROMOTION
4         1373      PROMOTION
...        ...            ...
3375      2492        SFPESTO
3376       893        SFPESTO
3377      3100  PRHONEYCHEESE
3378       836      TUNA&CRAB
3379      3267         PATELX

[3380 rows x 2 columns]

In [5]:
segment = segment.rename(columns={'Cluster':'Combo_Single_Prefered','segment': 'RFM_Segment','Favourite_piz_size':'favourite_pizza_size'})

In [6]:
segment

,CustomerID,Combo_Single_Prefered,RFM_Segment,favourite_pizza_size,favourite_voucher_lv1,favourite_voucher_lv2,favourite_channel
0,0,Single_item_prefered,potential,LARGE,PROMOTION,PROMOTION_BOGO,Delivery_STORE
1,1,Single_item_prefered,potential,REGULAR,PROMOTION,PROMOTION_B1G3,Delivery_CallCenter
2,2,Single_item_prefered,hibernating,REGULAR,PROMOTION,PROMOTION_BOGO,Delivery_CallCenter
3,3,Single_item_prefered,hibernating,LARGE,PROMOTION,PROMOTION_BOGO,Delivery_CallCenter
4,4,Single_item_prefered,hibernating,LARGE,PROMOTION,PROMOTION_B1G3,Delivery_WEBSITE
...,...,...,...,...,...,...,...
30989,266,Single_item_prefered,potential,LARGE,ALC,ALC_PIZZA,Food Aggregators_AGG-SHOPEEFOOD
30990,28733,Single_item_prefered,new customer,REGULAR,ALC,ALC_PIZZA,Food Aggregators_AGG-GRAB
30991,23875,Single_item_prefered,new customer,PERSONAL,ALC,ALC_PIZZA,Food Aggregators_AGG-SHOPEEFOOD
30992,5841,Single_item_prefered,new customer,PERSONAL,ALC,ALC_PIZZA,Take Away_STORE
30993,15757,Single_item_prefered,new customer,PERSONAL,ALC,ALC_PIZZA,Delivery_WEBSITE

In [7]:
merged = product_sales.merge(product_map, 
                             on = 'FoodCode',how='left').merge(voucher_map, 
                                                               on ='BillID', how='left').merge(segment, 
                                                                                               on = 'CustomerID', how='left').merge(product_map_nonprefix, 
                                                                                                                                    on = 'FoodCode', how='left').merge(RFM_value,
                                                                                                                                                                       on = 'CustomerID', how='left')

In [8]:
# merged.to_csv(r'Joined_Data.csv')

In [9]:
merged.columns

Index(['BillID', 'TransactionDate', 'TransactionTime', 'Channel', 'OrderFrom',
       'FatherCode', 'FoodCode', 'ItemTotalQuantity', 'NetAmount', 'LEVEL_1',
       'LEVEL_2', 'LEVEL_3', 'CustomerID', 'NAME', 'CATEGORIES', 'SIZE',
       'CRUSTS', 'FLAVOURS', 'VoucherCampaignName', 'VoucherValue',
       'Total_Bill_Amount_Apply', 'Combo_Single_Prefered', 'RFM_Segment',
       'favourite_pizza_size', 'favourite_voucher_lv1',
       'favourite_voucher_lv2', 'favourite_channel', 'NAME_NOPREFIX',
       'days_between_first_last_order', 'total_value', 'avg_value_per_order',
       'Mean_Days_Between_Purchase', 'Max_Days_Between_Purchase'],
      dtype='object')